# app/telegram/common/states.py
# Estados del flujo de reporte - Compartidos por todos los departamentos

ESPERAR_ACEPTACION = 0
MENU_PRINCIPAL = 1
TIPO = 2
CUENTA = 3
SUBTIPO_AGUA = 4
SUBTIPO_DRENAJE = 5
ELEGIR_UBICACION = 6
LOCALIDAD = 7
LOCALIDAD_SUGERENCIAS = 8
CALLE = 9
CALLE_SUGERENCIAS = 10
NUMERO = 11
DUPLICADO_CONFIRMACION = 12
ENTRE_CALLES = 13
DESCRIPCION = 14
EVIDENCIA = 15
CONFIRMACION = 16
CONSULTA_ID = 17
VERIFICAR_REPORTANTE = 18

# Estados para departamentos adicionales
# (se usarán cuando se activen, no rompen nada mientras tanto)
SUBTIPO_ASEO_PUBLICO = 19
SUBTIPO_ALUMBRADO_PUBLICO = 20
SUBTIPO_PARQUES_JARDINES = 21
SUBTIPO_ECOLOGIA = 22
SUBTIPO_SEGURIDAD_PUBLICA = 23
SUBTIPO_OBRA_PUBLICA = 24
SUBTIPO_BOMBEROS = 25

# Estados para registro de profesionales
REGISTRO_CONFIRMACION = 26

# Estados para encuesta de satisfacción
ENCUESTA_CALIFICACION = 27
ENCUESTA_VELOCIDAD = 28
ENCUESTA_COMENTARIO = 29
